name: CI Docker build

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - main
      - "[0-9].x"
jobs:
  build-and-push-worker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta-worker
        uses: docker/metadata-action@v4.0.1
        with:
          images: pilos/bbb-streaming-server
          flavor: |
            latest=auto
            prefix=worker
            suffix=
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch,prefix=dev-

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: src/worker
          push: true
          tags: ${{ steps.meta-worker.outputs.tags }}
          labels: ${{ steps.meta-worker.outputs.labels }}
          cache-from: type=registry,ref=pilos/bbb-streaming-server:worker-buildcache
          cache-to: type=registry,ref=pilos/bbb-streaming-server:worker-buildcache,mode=max

  build-and-push-controller-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta-controller
        uses: docker/metadata-action@v4.0.1
        with:
          images: pilos/bbb-streaming-server
          flavor: |
            latest=auto
            prefix=controller
            suffix=
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch,prefix=dev-

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: src/controller
          push: true
          tags: ${{ steps.meta-controller.outputs.tags }}
          labels: ${{ steps.meta-controller.outputs.labels }}
          cache-from: type=registry,ref=pilos/bbb-streaming-server:controller-buildcache
          cache-to: type=registry,ref=pilos/bbb-streaming-server:controller-buildcache,mode=max
