services:
  worker:
    build:
      context: src/worker
    environment:
      - NODE_DEBUG=bull
    volumes:
      - ./src/worker:/home/streaming
    depends_on:
      - redis
    deploy:
      mode: replicated
      replicas: 6
  controller:
    build:
      context: src/controller
    environment:
      - NODE_DEBUG=bull
    ports:
      - "80:3000"
    volumes:
        - ./src/controller:/home/streaming
    depends_on:
      - redis
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/d–∞ta:/root/redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
