services:
  worker:
    image: pilos/bbb-streaming-server:worker-1.0
    depends_on:
      - redis
    deploy:
      mode: replicated
      replicas: 5
  controller:
    image: pilos/bbb-streaming-server:controller-1.0
    ports:
      - "127.0.0.1:${APP_PORT:-3000}:3000"
    depends_on:
      - redis
  redis:
    image: redis:latest
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
