services:
  worker:
    build:
      context: src/worker
    environment:
      - NODE_DEBUG=bull
      - FFMPEG_BITRATE=10
      - FFMPEG_CRF=23
      - DEBUG=true
      - JSON_LOGS=false
      - LOG_LEVEL=debug
    volumes:
      - ./src/worker:/home/streaming
    depends_on:
      - redis
    deploy:
      mode: replicated
      replicas: 1
  controller:
    build:
      context: src/controller
    environment:
      - NODE_DEBUG=bull
      - FAILED_JOB_ATTEMPTS=1
    ports:
      - "127.0.0.1:${APP_PORT:-3000}:3000"
    volumes:
        - ./src/controller:/home/streaming
    depends_on:
      - redis
  redis:
    image: redis:latest
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
