name: CI Docker PR build

on:
  pull_request:
jobs:
  build-worker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: src/worker
          cache-from: type=registry,ref=pilos/bbb-streaming-server:worker-buildcache

  build-controller-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: src/controller
          cache-from: type=registry,ref=pilos/bbb-streaming-server:controller-buildcache
